feature_extract_enable : 0
point_filter_num : 2
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.3
cube_side_length : 20
debug : 0
grid_size : 40
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 1000 # 1000
laser_point_cov : 0.001 # 0.001
cam_fx: 1858.851674 
cam_fy: 1850.424325
cam_cx: 689.121011
cam_cy: 525.758177

common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"

preprocess:
    lidar_type: 1 # Livox Avia LiDAR
    scan_line: 6
    blind: 5 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    fov_degree:    90
    extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

camera:
    # img_topic: /usb_cam/image_raw
    # img_topic:  /camera/image_color
    img_topic: /hikcamera/image
    #xiyuan
    Rcl: [0.0229839, -0.9995804, -0.0176269,
          0.0050647,  0.0177477, -0.9998296, 
          0.9997230,  0.0228907,  0.0054705]
    Pcl: [-0.058, -0.015, 0.03] 

    # Rcl: [0.0229839,   0.0050647,   0.999723,
    #        -0.9995804,  0.0177477,   0.0228907, 
    #       -0.0176269, -0.9998296,   0.0054705]
    # Pcl: [-0.03007364,0.05790748,-0.01464129] 


