common:
  lidar_topic:  "/robot/dlio/odom_node/pointcloud/deskewed"                  # From FASTLIO2
  lidar_color_topic:  "/livox/color_lidar" #"/color_lidar"      # Pub color pointcloud
  odom_topic:  "/robot/dlio/odom_node/odom"                             # From FASTLIO2
  camera_topic:  "/hikcamera/image"
  frame_id: "livox_frame"                                   # From FASTLIO2 's  frame_link

mapping:
  # extrinsicT: [0.0229839,   0.0050647,   0.999723,  -0.03007364,
  #             -0.9995804,  0.0177477,   0.0228907,  0.05790748,
  #             -0.0176269, -0.9998296,   0.0054705, -0.01464129,
  #              0,          0,          0,          1]        #  lidar2camera 外参  From livox_camera_calib

  extrinsicT: [0.0229839, -0.9995804, -0.0176269, -0.058,
              0.0050647,  0.0177477, -0.9998296, -0.015,
              0.9997230,  0.0228907,  0.0054705, 0.03,
              0,0,0,1]  #  lidar2camera 外参  From livox_camera_calib


  intrisicT: [  1858.851674, 0.000000, 689.121011,
                0.000000, 1850.424325, 525.758177,
                0.000000, 0.000000, 1.000000]           # camera 内参

  ditortion: [ -0.025024, -0.068101, -0.001616, -0.004414, 0.000000]      # camera 畸变系数

savepcd:
  savePCDDirectory: "/catkin_ws/src/livox_color/PCD/"
